### ISSUE TITLE
Project setup

### ISSUE THREAD

**Issue by franzmoro** [franzmoro/property-mgmt#4]
## Tasks
- [x] eslint
- [x] config vars
- [x] dependencies (handlebars, tape, shot)
- [x] basic server
- [x] node routing
- [x] handlebars templates engine
- test
  - [x] runner file
  - [x] basic server test
  - [x] basic routes tests (routes exist, 404 response)
  - [x] travis-ci
